### ISSUE TITLE
New pagination / Update SDK

### ISSUE THREAD

**Issue by pocesar** [dtrungtin/actor-allrecipes-scraper#13]
Add new url formats support

**Comment by dtrungtin** [comment]
Fixed. https://github.com/dtrungtin/actor-allrecipes-scraper/commit/b32d0f765a96ce1d6ddfbfe8184394245938209e

**Comment by zpelechova** [comment]
Updated SDK, but the pagination is not fixed ( I created new issue for it).

**Comment by zpelechova** [comment]
Fixed.
